### PR TITLE
Make packageName optional

### PR DESCRIPTION
**Pull request by ghost**
This allows AMD modules to be compiled without a package name. In the case where packageName is blank, it will simply use the file name.

// @jnicklas & @burgestrand

### CODE REVIEW

**Comment by ryanflorence** [comment]
Thanks for the pull request but this won't work.

If two packages distribute files named "main" or "index" or anything really then you're hosed.

For more information, read up on AMD packages: http://requirejs.org/docs/api.html#packages.

**Comment by ryanflorence** [comment]
I'm curious what use-case you are attempting to solve here and maybe I can help point you in the right direction.

**Comment by ghost** [comment]
In our case, we're building an application, not a library for others to consume. There's really no reason we want to namespace all files in the application. It simply adds unnecessary ceremony to every single require statement. If we ever have collisions, we can easily resolve them.

**Comment by ryanflorence** [comment]
It is best practice to register your application as a package and then point `baseUrl` to your vendor directory to remove nearly all ceremony. Once inside your `app/main` file, use relative module ids.

``` js
// one time config
require.config({
  baseUrl: 'vendor/',
  packages: [{name: 'app', location: '../app'}]
});
```

And then `app/main.js` looks like this:

``` js
// this works if you have `vendor/jquery.js` and `vendor/lodash.js`
import $ from 'jquery';
import { each } from 'lodash';

// now your app stuff with relative ids
import Foo from './foo';
import { isArray, toArray } from './lang/array';
// etc.
```

I do not see the ceremony :)

**Comment by ryanflorence** [comment]
> If we ever have collisions, we can easily resolve them

It is my job as the library author to prevent this problem if I can and encourage best practices with AMD, especially since named AMD is probably the worst thing you can do to a module.

**Pull request closed without merging**
